import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import '@/app/globals.css'
import { Toaster } from 'sonner'
import { cn } from '@/lib/utils'
import Navbar from '@/components/Navbar'

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'auto',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <main className="relative flex flex-col min-h-screen">
          <Navbar />
          <div className="flex-1 flex-grow">
            {children}
            <Toaster position="bottom-right" richColors expand={true} />
          </div>
        </main>
      </body>
    </html>
  )
}
