import {
  SunSnow,
  GripVertical,
  Settings,
  Delete,
  ChevronLeft,
  XCircleIcon,
  Pencil,
  ShieldMinus,
  Circle,
  LockIcon,
  MoreHorizontal,
  Loader,
  Table,
} from 'lucide-react'

export const Icons = {
  logo: SunSnow,
  handle: GripVertical,
  settings: Settings,
  delete: Delete,
  chevronLeft: ChevronLeft,
  xCircleIcon: XCircleIcon,
  pencil: Pencil,
  shield: ShieldMinus,
  circle: Circle,
  lock: LockIcon,
  dots: MoreHorizontal,
  spinner: Loader,
  table: Table,
}
