import {
  SunSnow,
  GripVertical,
  Settings,
  Delete,
  ChevronLeft,
  XCircleIcon,
  Pencil,
  ShieldMinus,
  Circle,
  LockIcon,
  MoreHorizontal,
  Loader,
  Table,
  LayoutList,
  CheckCircle2,
  PackagePlus,
  ChevronLeftIcon,
  BadgePlus,
  Milestone,
  Trash2,
  Users,
  Tent,
  Paintbrush2,
} from 'lucide-react'

export const Icons = {
  logo: SunSnow,
  handle: GripVertical,
  settings: Settings,
  delete: Delete,
  chevronLeft: ChevronLeft,
  xCircleIcon: XCircleIcon,
  pencil: Pencil,
  shield: ShieldMinus,
  circle: Circle,
  lock: LockIcon,
  dots: MoreHorizontal,
  spinner: Loader,
  table: Table,
  list: LayoutList,
  check: CheckCircle2,
  project: PackagePlus,
  chevron_left: ChevronLeftIcon,
  add_milestone: BadgePlus,
  milestone: Milestone,
  team: Users,
  trash: Trash2,
  colors: Paintbrush2,
}
